namespace TALXIS.CLI.Features.Workspace.Localization;

/// <summary>
/// Built-in source-string filter for Power Platform system attributes that are
/// inherited by every entity (createdon, modifiedon, owner, statecode, activity-
/// related fields, etc.). Power Platform localizes these itself based on the
/// user's locale, so they should not appear in translation exports.
///
/// The list is a snapshot of the localizable strings present in the DevKit
/// pp-entity Entity.xml template. It is hard-coded — no template files are read
/// at runtime. Refresh this list when the underlying platform / template
/// schema gains or removes system attributes.
/// </summary>
public static class SystemAttributesFilter
{
    public static readonly HashSet<string> Strings = new(StringComparer.Ordinal)
    {
        "(Deprecated) Process Stage",
        "(Deprecated) Traversed Path",
        "Active",
        "Activity",
        "Activity Additional Parameters",
        "Activity Status",
        "Activity Type",
        "Actual Duration",
        "Actual End",
        "Actual Start",
        "Actual duration of the activity in minutes.",
        "Actual end time of the activity.",
        "Actual start time of the activity.",
        "Additional information provided by the external application as JSON. For internal use only.",
        "Appointment Type",
        "BCC",
        "Blind Carbon-copy (bcc) recipients of the activity.",
        "CC",
        "Canceled",
        "Carbon-copy (cc) recipients of the activity.",
        "Choose the service level agreement (SLA) that you want to apply to the case record.",
        "Completed",
        "Contains the date and time stamp of the last on hold time.",
        "Created By",
        "Created By (Delegate)",
        "Created On",
        "Customer with which the activity is associated.",
        "Customers",
        "Date Created",
        "Date Delivery Last Attempted",
        "Date Sent",
        "Date and time that the record was migrated.",
        "Date and time when activity was last modified.",
        "Date and time when the activity was created.",
        "Date and time when the activity was sent.",
        "Date and time when the delivery of the activity was last attempted.",
        "Date and time when the record was created.",
        "Date and time when the record was modified.",
        "Delay activity processing until",
        "Delivery Priority",
        "Description",
        "Description of the activity.",
        "Due Date",
        "ExampleEntityDisplayName",
        "ExampleEntityPluralDisplayName",
        "Exchange Item ID",
        "Exchange WebLink",
        "For internal use only.",
        "From",
        "High",
        "Import Sequence Number",
        "Inactive",
        "Information regarding whether the activity is a regular activity type or event type.",
        "Information regarding whether the activity was billed as part of resolving a case.",
        "Information regarding whether the activity was created from a workflow rule.",
        "Is Billed",
        "Is Private",
        "Is Regular Activity",
        "Is Workflow Created",
        "Last On Hold Time",
        "Last SLA applied",
        "Last SLA that was applied to this case. This field is for internal use only.",
        "Last Updated",
        "Left Voice Mail",
        "Left Voice Mail.",
        "Left the voice mail",
        "List of optional attendees for the activity.",
        "List of required attendees for the activity.",
        "Low",
        "Modified By",
        "Modified By (Delegate)",
        "Modified On",
        "Name",
        "No",
        "Normal",
        "Not Recurring",
        "On Hold Time (Minutes)",
        "Open",
        "Optional Attendees",
        "Organization Id",
        "Organizer",
        "Outsource Vendors",
        "Outsource vendor with which activity is associated.",
        "Owner",
        "Owner Id",
        "Owning Business Unit",
        "Owning Team",
        "Owning User",
        "Person who is the receiver of the activity.",
        "Person who organized the activity.",
        "Person who the activity is from.",
        "Priority",
        "Priority of delivery of the activity to the email server.",
        "Priority of the activity.",
        "Process",
        "Reason for the status of the ExampleEntityDisplayName",
        "Reason for the status of the activity.",
        "Record Created On",
        "Recurring Exception",
        "Recurring Future Exception",
        "Recurring Instance",
        "Recurring Instance Type",
        "Recurring Master",
        "Regarding",
        "Required Attendees",
        "Resources",
        "SLA",
        "Scheduled",
        "Scheduled Duration",
        "Scheduled duration of the activity, specified in minutes.",
        "Scheduled end time of the activity.",
        "Scheduled start time of the activity.",
        "Sender's Mailbox",
        "Sequence number of the import that created this record.",
        "Series Id",
        "Shows how contact about the social activity originated, such as from Twitter or Facebook. This field is read-only.",
        "Shows how long, in minutes, that the record was on hold.",
        "Shows the date and time by which the activities are sorted.",
        "Shows the web link of Activity of type email.",
        "Social Channel",
        "Sort Date",
        "Start Date",
        "Status",
        "Status Reason",
        "Status of the ExampleEntityDisplayName",
        "Status of the activity.",
        "Subject",
        "Subject associated with the activity.",
        "The message id of activity which is returned from Exchange Server.",
        "Time Zone Rule Version Number",
        "Time zone code that was in use when the record was created.",
        "To",
        "Type of activity.",
        "Type of instance of a recurring series.",
        "UTC Conversion Time Zone Code",
        "Unique identifier for entity instances",
        "Unique identifier for the business unit that owns the record",
        "Unique identifier for the organization",
        "Unique identifier for the team that owns the record.",
        "Unique identifier for the user that owns the record.",
        "Unique identifier of the Process.",
        "Unique identifier of the Stage.",
        "Unique identifier of the activity.",
        "Unique identifier of the business unit that owns the activity.",
        "Unique identifier of the delegate user who created the activitypointer.",
        "Unique identifier of the delegate user who created the record.",
        "Unique identifier of the delegate user who last modified the activitypointer.",
        "Unique identifier of the delegate user who modified the record.",
        "Unique identifier of the mailbox associated with the sender of the email message.",
        "Unique identifier of the object with which the activity is associated.",
        "Unique identifier of the team that owns the activity.",
        "Unique identifier of the user or team who owns the activity.",
        "Unique identifier of the user that owns the activity.",
        "Unique identifier of the user who created the activity.",
        "Unique identifier of the user who created the record.",
        "Unique identifier of the user who modified the record.",
        "Unique identifier of user who last modified the activity.",
        "Uniqueidentifier specifying the id of recurring series of an instance.",
        "Users or facility/equipment that are required for the activity.",
        "Yes",
    };

    /// <summary>
    /// Returns true when the given site should be excluded from translation
    /// because its source matches a Power Platform system attribute string.
    /// Currently scoped to Entity.xml files only — forms, ribbon, and saved
    /// queries are not affected.
    /// </summary>
    public static bool ShouldExclude(LocalizableSite site) =>
        IsEntityXml(site.FileRelativePath) && Strings.Contains(site.Source);

    private static bool IsEntityXml(string fileRelPath) =>
        fileRelPath.EndsWith("/Entity.xml", StringComparison.OrdinalIgnoreCase);
}
