namespace TALXIS.CLI.Features.Environment.CustomApi;

/// <summary>Custom API definition with its parameters, used as OpenAPI generation input.</summary>
internal sealed record CustomApiDefinition(
    string UniqueName,
    string? DisplayName,
    string? Description,
    int BindingType,
    string? BoundEntity,
    bool IsFunction,
    IReadOnlyList<CustomApiParameter> RequestParameters,
    IReadOnlyList<CustomApiParameter> ResponseProperties);

/// <summary>A request parameter or response property of a Custom API.</summary>
internal sealed record CustomApiParameter(
    string UniqueName,
    string? DisplayName,
    int TypeCode,
    bool IsOptional);

/// <summary>
/// Builds an OpenAPI 3.0 document (as a nested dictionary, serialized by the caller)
/// from Custom API definitions. Actions become POST operations, functions become GET.
/// </summary>
internal static class CustomApiOpenApiBuilder
{
    internal static Dictionary<string, object?> Build(
        IReadOnlyList<CustomApiDefinition> apis,
        string title,
        string version,
        string? environmentUrl)
    {
        var paths = new Dictionary<string, object?>();
        foreach (var api in apis.OrderBy(a => a.UniqueName, StringComparer.OrdinalIgnoreCase))
            paths[PathFor(api)] = BuildPathItem(api);

        var document = new Dictionary<string, object?>
        {
            ["openapi"] = "3.0.3",
            ["info"] = new Dictionary<string, object?>
            {
                ["title"] = title,
                ["version"] = version,
                ["description"] = "Custom APIs registered in the Dataverse environment. Generated by TALXIS CLI.",
            },
            ["paths"] = paths,
        };

        if (!string.IsNullOrWhiteSpace(environmentUrl))
        {
            document["servers"] = new List<object?>
            {
                new Dictionary<string, object?> { ["url"] = $"{environmentUrl.TrimEnd('/')}/api/data/v9.2" },
            };
        }

        return document;
    }

    internal static string PathFor(CustomApiDefinition api) => api.BindingType switch
    {
        1 => $"/{api.BoundEntity}({{id}})/Microsoft.Dynamics.CRM.{api.UniqueName}",
        2 => $"/{api.BoundEntity}/Microsoft.Dynamics.CRM.{api.UniqueName}",
        _ => $"/{api.UniqueName}",
    };

    private static Dictionary<string, object?> BuildPathItem(CustomApiDefinition api)
    {
        var operation = new Dictionary<string, object?>
        {
            ["operationId"] = api.UniqueName,
            ["summary"] = api.DisplayName ?? api.UniqueName,
            ["responses"] = BuildResponses(api),
        };
        if (!string.IsNullOrWhiteSpace(api.Description))
            operation["description"] = api.Description;

        var parameters = new List<object?>();
        if (api.BindingType == 1)
        {
            parameters.Add(new Dictionary<string, object?>
            {
                ["name"] = "id",
                ["in"] = "path",
                ["required"] = true,
                ["schema"] = new Dictionary<string, object?> { ["type"] = "string", ["format"] = "uuid" },
                ["description"] = $"Primary key of the bound {api.BoundEntity} record.",
            });
        }

        if (api.IsFunction)
        {
            foreach (var p in api.RequestParameters)
            {
                parameters.Add(new Dictionary<string, object?>
                {
                    ["name"] = p.UniqueName,
                    ["in"] = "query",
                    ["required"] = !p.IsOptional,
                    ["schema"] = SchemaFor(p.TypeCode),
                });
            }
        }
        else if (api.RequestParameters.Count > 0)
        {
            operation["requestBody"] = new Dictionary<string, object?>
            {
                ["required"] = api.RequestParameters.Any(p => !p.IsOptional),
                ["content"] = JsonContent(ObjectSchema(api.RequestParameters, includeRequired: true)),
            };
        }

        if (parameters.Count > 0)
            operation["parameters"] = parameters;

        return new Dictionary<string, object?> { [api.IsFunction ? "get" : "post"] = operation };
    }

    private static Dictionary<string, object?> BuildResponses(CustomApiDefinition api)
    {
        if (api.ResponseProperties.Count == 0)
        {
            return new Dictionary<string, object?>
            {
                ["204"] = new Dictionary<string, object?> { ["description"] = "No content." },
            };
        }

        return new Dictionary<string, object?>
        {
            ["200"] = new Dictionary<string, object?>
            {
                ["description"] = "Success.",
                ["content"] = JsonContent(ObjectSchema(api.ResponseProperties, includeRequired: false)),
            },
        };
    }

    private static Dictionary<string, object?> ObjectSchema(IReadOnlyList<CustomApiParameter> parameters, bool includeRequired)
    {
        var properties = new Dictionary<string, object?>();
        foreach (var p in parameters)
            properties[p.UniqueName] = SchemaFor(p.TypeCode);

        var schema = new Dictionary<string, object?>
        {
            ["type"] = "object",
            ["properties"] = properties,
        };

        if (includeRequired)
        {
            var required = parameters.Where(p => !p.IsOptional).Select(p => (object?)p.UniqueName).ToList();
            if (required.Count > 0) schema["required"] = required;
        }

        return schema;
    }

    private static Dictionary<string, object?> SchemaFor(int typeCode)
    {
        var (type, format, itemsType) = CustomApiMaps.ToOpenApiSchema(typeCode);
        var schema = new Dictionary<string, object?> { ["type"] = type };
        if (format is not null) schema["format"] = format;
        if (itemsType is not null) schema["items"] = new Dictionary<string, object?> { ["type"] = itemsType };
        return schema;
    }

    private static Dictionary<string, object?> JsonContent(Dictionary<string, object?> schema) => new()
    {
        ["application/json"] = new Dictionary<string, object?> { ["schema"] = schema },
    };
}
